import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'smartdine_project.settings')
django.setup()

from core.models import Restaurant

def seed_restaurants():
    restaurants_data = [
        {
            'name': 'Hari Bhavanam',
            'address': 'Avinashi Road, Peelamedu, Coimbatore',
            'latitude': 11.0168,
            'longitude': 77.0062,
            'cuisines': 'South Indian, North Indian, Chinese',
            'price_range': '₹200-400',
            'average_cost': 300,
            'rating': 4.3,
            'tags': 'family-friendly, spacious, casual, vegetarian-options',
            'must_try_dishes': 'Ghee Roast Dosa, Paneer Butter Masala, Gobi Manchurian',
            'special_recognition': 'Popular family restaurant with diverse menu',
            'google_maps_link': 'https://maps.google.com/?q=Hari+Bhavanam+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Annapoorna',
            'address': 'Sathy Road, Ganapathy, Coimbatore',
            'latitude': 11.0502,
            'longitude': 76.9802,
            'cuisines': 'South Indian',
            'price_range': '₹100-250',
            'average_cost': 150,
            'rating': 4.2,
            'tags': 'budget-friendly, authentic, quick-service, vegetarian',
            'must_try_dishes': 'Mini Tiffin, Pongal, Filter Coffee',
            'special_recognition': 'Legendary South Indian chain since 1968',
            'google_maps_link': 'https://maps.google.com/?q=Annapoorna+Ganapathy+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Shree Anandhaas',
            'address': 'RS Puram, Coimbatore',
            'latitude': 11.0062,
            'longitude': 76.9563,
            'cuisines': 'South Indian, Sweets, Chaat',
            'price_range': '₹150-300',
            'average_cost': 200,
            'rating': 4.4,
            'tags': 'sweets, snacks, family-friendly, vegetarian',
            'must_try_dishes': 'Mysore Pak, Samosa, Masala Dosa',
            'special_recognition': 'Famous for traditional sweets and snacks',
            'google_maps_link': 'https://maps.google.com/?q=Shree+Anandhaas+RS+Puram',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Sree Annapoorna Sree Gowrishankar',
            'address': 'East Arokiasamy Road, RS Puram, Coimbatore',
            'latitude': 11.0053,
            'longitude': 76.9579,
            'cuisines': 'South Indian, North Indian',
            'price_range': '₹200-400',
            'average_cost': 250,
            'rating': 4.5,
            'tags': 'traditional, spacious, family-dining, vegetarian',
            'must_try_dishes': 'Ghee Podi Dosa, Curd Rice, Thali',
            'special_recognition': 'Iconic restaurant known for authentic Tamil cuisine',
            'google_maps_link': 'https://maps.google.com/?q=SASG+RS+Puram+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Kovai Biriyani',
            'address': 'Trichy Road, Singanallur, Coimbatore',
            'latitude': 10.9933,
            'longitude': 77.0254,
            'cuisines': 'Biryani, South Indian',
            'price_range': '₹150-350',
            'average_cost': 250,
            'rating': 4.3,
            'tags': 'biryani, spicy, non-vegetarian, delivery-friendly',
            'must_try_dishes': 'Chicken Biryani, Mutton Biryani, Biryani Rice',
            'special_recognition': 'Best authentic Kongu-style biryani',
            'google_maps_link': 'https://maps.google.com/?q=Kovai+Biriyani+Singanallur',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': True
        },
        {
            'name': "Ponnusamy's Biriyani",
            'address': 'Avinashi Road, Coimbatore',
            'latitude': 11.0240,
            'longitude': 76.9991,
            'cuisines': 'Biryani, Chettinad',
            'price_range': '₹200-450',
            'average_cost': 300,
            'rating': 4.4,
            'tags': 'spicy, flavorful, non-vegetarian, traditional',
            'must_try_dishes': 'Mutton Biryani, Chicken 65, Chettinad Fish Curry',
            'special_recognition': 'Famous Chennai chain, renowned for Chettinad flavors',
            'google_maps_link': 'https://maps.google.com/?q=Ponnusamys+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': True
        },
        {
            'name': 'Haribhavanam Thattukada',
            'address': 'Saibaba Colony, Coimbatore',
            'latitude': 11.0188,
            'longitude': 77.0046,
            'cuisines': 'North Indian, Chinese, Tandoor',
            'price_range': '₹250-500',
            'average_cost': 350,
            'rating': 4.2,
            'tags': 'casual, open-air, night-dining, non-vegetarian',
            'must_try_dishes': 'Butter Chicken, Tandoori Chicken, Garlic Naan',
            'special_recognition': 'Popular late-night street food style dining',
            'google_maps_link': 'https://maps.google.com/?q=Haribhavanam+Thattukada+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': True
        },
        {
            'name': 'That Barbeque Place',
            'address': 'DB Road, RS Puram, Coimbatore',
            'latitude': 11.0070,
            'longitude': 76.9588,
            'cuisines': 'Barbeque, Continental, North Indian',
            'price_range': '₹800-1500',
            'average_cost': 1000,
            'rating': 4.6,
            'tags': 'buffet, premium, grilled, upscale-dining',
            'must_try_dishes': 'BBQ Buffet, Grilled Prawns, Sizzlers',
            'special_recognition': 'Premium live grill buffet experience',
            'google_maps_link': 'https://maps.google.com/?q=That+Barbeque+Place+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': False
        },
        {
            'name': 'Hotel Junior Kuppanna',
            'address': 'Avinashi Road, Coimbatore',
            'latitude': 11.0215,
            'longitude': 76.9980,
            'cuisines': 'Chettinad, South Indian, Biryani',
            'price_range': '₹300-600',
            'average_cost': 400,
            'rating': 4.5,
            'tags': 'authentic, spicy, traditional, non-vegetarian',
            'must_try_dishes': 'Mutton Chukka, Nethili Fry, Crab Masala',
            'special_recognition': 'Authentic Kongu Nadu Chettinad cuisine',
            'google_maps_link': 'https://maps.google.com/?q=Junior+Kuppanna+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': False
        },
        {
            'name': 'Thalappakatti Restaurant',
            'address': 'Trichy Road, Singanallur, Coimbatore',
            'latitude': 10.9940,
            'longitude': 77.0270,
            'cuisines': 'Biryani, South Indian',
            'price_range': '₹200-450',
            'average_cost': 300,
            'rating': 4.3,
            'tags': 'biryani, traditional, spicy, non-vegetarian',
            'must_try_dishes': 'Dindigul Biryani, Chicken 65, Salna',
            'special_recognition': 'Famous Dindigul-style biryani chain',
            'google_maps_link': 'https://maps.google.com/?q=Thalappakatti+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': True
        },
        {
            'name': 'Geethas Veg Restaurant',
            'address': 'Oppanakara Street, Coimbatore',
            'latitude': 11.0050,
            'longitude': 76.9650,
            'cuisines': 'South Indian',
            'price_range': '₹100-200',
            'average_cost': 150,
            'rating': 4.1,
            'tags': 'budget-friendly, local-favorite, vegetarian, quick',
            'must_try_dishes': 'Parotta, Veg Kurma, Idiyappam',
            'special_recognition': 'Local favorite for authentic Tamil breakfast',
            'google_maps_link': 'https://maps.google.com/?q=Geethas+Veg+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Pavilion Restaurant',
            'address': 'Race Course Road, Coimbatore',
            'latitude': 11.0096,
            'longitude': 76.9633,
            'cuisines': 'Multi-cuisine, Continental, Chinese',
            'price_range': '₹600-1200',
            'average_cost': 800,
            'rating': 4.4,
            'tags': 'upscale, fine-dining, elegant, multi-cuisine',
            'must_try_dishes': 'Tandoori Platter, Pasta, Desserts',
            'special_recognition': 'Premium hotel restaurant with elegant ambiance',
            'google_maps_link': 'https://maps.google.com/?q=Pavilion+Restaurant+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': False
        },
        {
            'name': 'Oyalo Pizza',
            'address': 'Avinashi Road, Peelamedu, Coimbatore',
            'latitude': 11.0190,
            'longitude': 77.0070,
            'cuisines': 'Italian, Pizza, Fast Food',
            'price_range': '₹300-600',
            'average_cost': 400,
            'rating': 4.2,
            'tags': 'casual, pizza, quick-bite, delivery',
            'must_try_dishes': 'Wood-fired Pizza, Pasta, Garlic Bread',
            'special_recognition': 'Popular local pizza chain',
            'google_maps_link': 'https://maps.google.com/?q=Oyalo+Pizza+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': True
        },
        {
            'name': 'Kongu Nadu Oota Unavagam',
            'address': 'Avinashi Road, Coimbatore',
            'latitude': 11.0250,
            'longitude': 77.0010,
            'cuisines': 'South Indian, Kongu Nadu Cuisine',
            'price_range': '₹150-300',
            'average_cost': 200,
            'rating': 4.3,
            'tags': 'traditional, authentic, budget-friendly, vegetarian',
            'must_try_dishes': 'Oota Meals, Arisi Paruppu Sadam, Karakuzhambu',
            'special_recognition': 'Authentic Kongu Nadu traditional meals',
            'google_maps_link': 'https://maps.google.com/?q=Kongu+Nadu+Oota+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Maaplae',
            'address': 'Peelamedu, Coimbatore',
            'latitude': 11.0178,
            'longitude': 77.0092,
            'cuisines': 'South Indian, Chettinad',
            'price_range': '₹250-500',
            'average_cost': 350,
            'rating': 4.4,
            'tags': 'authentic, homely, traditional, non-vegetarian',
            'must_try_dishes': 'Chicken Chettinad, Kaadai Curry, Parotta',
            'special_recognition': 'Home-style Chettinad cooking',
            'google_maps_link': 'https://maps.google.com/?q=Maaplae+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': False
        },
        {
            'name': 'The French Door',
            'address': 'Avinashi Road, Coimbatore',
            'latitude': 11.0205,
            'longitude': 77.0055,
            'cuisines': 'Continental, French, Bakery',
            'price_range': '₹400-800',
            'average_cost': 550,
            'rating': 4.5,
            'tags': 'bakery, cafe, elegant, desserts',
            'must_try_dishes': 'Croissants, Quiche, French Pastries',
            'special_recognition': 'Premium French bakery and cafe',
            'google_maps_link': 'https://maps.google.com/?q=The+French+Door+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': False
        },
        {
            'name': 'Cafe Coffee Day - Brookefields',
            'address': 'Brookefields Mall, Sukrawarpettai, Coimbatore',
            'latitude': 11.0269,
            'longitude': 77.0024,
            'cuisines': 'Cafe, Beverages, Snacks',
            'price_range': '₹200-400',
            'average_cost': 250,
            'rating': 4.0,
            'tags': 'cafe, hangout, coffee, casual',
            'must_try_dishes': 'Cappuccino, Cold Coffee, Sandwiches',
            'special_recognition': 'Popular cafe chain for coffee lovers',
            'google_maps_link': 'https://maps.google.com/?q=CCD+Brookefields+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': True,
            'is_open_late': True
        },
        {
            'name': 'Peelamedu Thattu Kadai',
            'address': 'Avinashi Road, Peelamedu, Coimbatore',
            'latitude': 11.0192,
            'longitude': 77.0082,
            'cuisines': 'Street Food, Chinese, North Indian',
            'price_range': '₹150-350',
            'average_cost': 200,
            'rating': 4.1,
            'tags': 'street-food, late-night, casual, budget-friendly',
            'must_try_dishes': 'Fried Rice, Gobi Manchurian, Kothu Parotta',
            'special_recognition': 'Popular late-night street food spot',
            'google_maps_link': 'https://maps.google.com/?q=Peelamedu+Thattu+Kadai+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': True
        },
        {
            'name': 'Anjappar Chettinad',
            'address': 'Trichy Road, Coimbatore',
            'latitude': 10.9925,
            'longitude': 77.0260,
            'cuisines': 'Chettinad, South Indian, Biryani',
            'price_range': '₹300-600',
            'average_cost': 400,
            'rating': 4.3,
            'tags': 'spicy, authentic, non-vegetarian, chain',
            'must_try_dishes': 'Chicken Chettinad, Mutton Sukka, Biryani',
            'special_recognition': 'Famous chain for authentic Chettinad flavors',
            'google_maps_link': 'https://maps.google.com/?q=Anjappar+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': True
        },
        {
            'name': 'Bawarchi Restaurant',
            'address': 'RS Puram, Coimbatore',
            'latitude': 11.0058,
            'longitude': 76.9571,
            'cuisines': 'North Indian, Mughlai, Biryani',
            'price_range': '₹250-500',
            'average_cost': 350,
            'rating': 4.2,
            'tags': 'traditional, rich-flavors, non-vegetarian, family',
            'must_try_dishes': 'Hyderabadi Biryani, Butter Chicken, Kebabs',
            'special_recognition': 'Known for rich Mughlai and North Indian cuisine',
            'google_maps_link': 'https://maps.google.com/?q=Bawarchi+RS+Puram+Coimbatore',
            'swiggy_link': 'https://www.swiggy.com',
            'zomato_link': 'https://www.zomato.com',
            'is_veg': False,
            'is_open_late': False
        }
    ]

    Restaurant.objects.all().delete()

    for data in restaurants_data:
        Restaurant.objects.create(**data)
        print(f"Created: {data['name']}")

    print(f"\nSuccessfully seeded {len(restaurants_data)} restaurants!")

if __name__ == '__main__':
    seed_restaurants()
