# Generated by Django 5.0.1 on 2025-12-15 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('cuisines', models.CharField(max_length=300)),
                ('price_range', models.CharField(max_length=50)),
                ('average_cost', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('tags', models.CharField(max_length=500)),
                ('must_try_dishes', models.TextField()),
                ('special_recognition', models.CharField(blank=True, max_length=300)),
                ('google_maps_link', models.URLField()),
                ('swiggy_link', models.URLField(blank=True)),
                ('zomato_link', models.URLField(blank=True)),
                ('is_veg', models.BooleanField(default=False)),
                ('is_open_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'restaurants',
                'indexes': [models.Index(fields=['rating'], name='restaurants_rating_93f534_idx'), models.Index(fields=['average_cost'], name='restaurants_average_02e546_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('instagram', 'Instagram'), ('friend', 'Friend Recommendation'), ('youtube', 'YouTube'), ('blog', 'Blog/Article'), ('other', 'Other')], max_length=50)),
                ('google_maps_link', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_discoveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_discoveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('user_location_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('user_location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
            options={
                'db_table': 'favorites',
                'unique_together': {('user', 'restaurant')},
            },
        ),
    ]
